### ISSUE TITLE
Discuss: When to trigger a re-ingest?

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/openvault3_deploy#39]
If the Solr config is changed, 3 things need to happen:
1. need to copy the solr config to jetty with `jetty:config` task
2. restart jetty with `jetty:restart` task (which may not exist yet)
3. re-ingest, which requires an up-to-date source file, and can take hours.

A re-ingest is too expensive to do for every deployment. Doing `jetty:config` without doing `jetty:restart` is pointless, so those two need to be paired together always. However, you don't want to `jetty:config`, `jetty:restart` without doing a re-ingest, because that leads to a mismatch between the current state of the index and the solr config, which will cause nasty errors.

So all 3 of these need to happen together, but only when the solr config is changed.

The status quo is for developers to just know when a re-ingest is needed, and do them accordingly.

One way to automate it would be to:
1. add some logic in the `before:deploy` hook (or wherever appropriate) to check the git log for changes to `solr_conf/solrconfig.xml` or `solr_conf/schema.xml`.
2. If a change is detected, stop the deployment, and print a message that says something like:
   
   ```
   This deployment requires a re-ingest which may take several hours to complete. To deploy and re-ingest run:
   
       bundle exec cap demo deploy OV_HOST=1.2.3.4 OV_SSH_KEY=~/.ssh/key.pem OV_REINGEST=true OV_PBCORE=path/to/pbcore
   
   replacing `path/to/pbcore` with the path to the file you want to ingest.
   
   To deploy without re-ingesting (not recommended!) run
   
       bundle exec cap demo deploy OV_HOST=1.2.3.4 OV_SSH_KEY=~/.ssh/key.pem OV_REINGEST=skip
   ```
3.  Add logic that recognizes `OV_REINGEST`, and that requires a value for `OV_PBCORE` when `OV_REINGEST=true` is present.

@mccalluc is that sane? Or should we just stick with status quo?

**Comment by singlesoliloquy** [comment]
@afred close this?

**Comment by afred** [comment]
Yes we can close. The broader issue of when and how to do large, possibly full, reindexing of the catalog remains an ongoing use case for which we have _**not**_ settled on a standard approach. We _**should**_ figure this out, but probably using a different strategy than the one outlined above.
