### ISSUE TITLE
Run cap tasks for multiple hosts, that each use a different key pair

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/openvault3_deploy#54]
**Done when** I can run cap tasks such as `deploy` and `ingest` for multiple hosts.

**Comment by singlesoliloquy** [comment]
@afred close this?

**Comment by afred** [comment]
Yes. Afaik, we no longer have a use case for keeping the indexes of Demo and Prod the same, because we're no longer doing blue/green deployment.
